title: elephant - 团队规范
subtitle: "Team Guidelines"
description: "Best Guidelines For Front-End Developer."
author: 大象集团信息技术部
language: zh-cn
timezone: UTC
url: http://guide.elephant-fe/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:elephant-fe/guide.git
  branch: gh-pages

disqus_shortname:
# google_analytics: UA-4910098-10
# baidu_analytics: bb4b770d7fdf4e05245cd1327199d813
fb_admins: 100000247608790
swiftype_key: nxhXzi1rDss_9_P_6zBa
# twitter: o2circle
github: elephant-fe/guide
gh:
  user: elephant-fe
  repo: guide
